Repository adtzlr/felupe, pull requests merged in 2024-05, with the labels that each got.

#754 Fix gradient-evaluation in `NeoHookeCompressible(lmbda=None)`
  CHANGELOG.md
  src/felupe/__about__.py
  src/felupe/constitution/_models_hyperelasticity.py
  src/felupe/dof/_boundary.py
Labels: bug

#755 Fix `MaterialStrain.plot()`
  CHANGELOG.md
  src/felupe/constitution/_view.py
Labels: bug

#756 Add the isotropic-hyperelastic Alexander model
  CHANGELOG.md
  docs/felupe/constitution.rst
  examples/ex13_morph-rubber-wheel.py
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/_models_hyperelasticity_ad.py
  tests/test_constitution.py
Labels: enhancement

#758 Re-organize the constitution module
  .github/workflows/upload-codecov.yml
  docs/felupe/constitution.rst
  src/felupe/constitution/__init__.py
  src/felupe/constitution/_material.py
  src/felupe/constitution/_material_ad.py
  src/felupe/constitution/hyperelasticity/__init__.py
  src/felupe/constitution/hyperelasticity/_hyperelastic.py
  src/felupe/constitution/hyperelasticity/_neo_hooke_compressible.py
  src/felupe/constitution/hyperelasticity/_neo_hooke_nearly_incompressible.py
  src/felupe/constitution/hyperelasticity/_volumetric.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_alexander.py
  src/felupe/constitution/hyperelasticity/models/_arruda_boyce.py
  src/felupe/constitution/hyperelasticity/models/_extended_tube.py
  src/felupe/constitution/hyperelasticity/models/_finite_strain_viscoelastic.py
  src/felupe/constitution/hyperelasticity/models/_helpers.py
  src/felupe/constitution/hyperelasticity/models/_models_hyperelasticity_ad.py
  src/felupe/constitution/hyperelasticity/models/_mooney_rivlin.py
  src/felupe/constitution/hyperelasticity/models/_neo_hooke.py
  src/felupe/constitution/hyperelasticity/models/_ogden.py
  src/felupe/constitution/hyperelasticity/models/_saint_venant_kirchhoff.py
  src/felupe/constitution/hyperelasticity/models/_third_order_deformation.py
  src/felupe/constitution/hyperelasticity/models/_van_der_waals.py
  src/felupe/constitution/hyperelasticity/models/_yeoh.py
  src/felupe/constitution/linear_elasticity/__init__.py
  src/felupe/constitution/linear_elasticity/_lame_converter.py
  src/felupe/constitution/linear_elasticity/_linear_elastic.py
  src/felupe/constitution/linear_elasticity/_linear_elastic_large_strain.py
  src/felupe/constitution/pseudo_elasticity/__init__.py
  src/felupe/constitution/pseudo_elasticity/_ogden_roxburgh.py
  src/felupe/constitution/small_strain/__init__.py
  src/felupe/constitution/small_strain/_material_strain.py
  src/felupe/constitution/small_strain/models/__init__.py
  src/felupe/constitution/small_strain/models/_linear_elastic.py
  src/felupe/constitution/small_strain/models/_linear_elastic_plastic_isotropic.py
  tox.ini
Labels: enhancement

#759 Delete _models_hyperelasticity_ad.py
  src/felupe/constitution/hyperelasticity/models/_models_hyperelasticity_ad.py
Labels: enhancement

#761 Fix the Alexander model
  CHANGELOG.md
  src/felupe/constitution/_view.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_alexander.py
  tests/test_constitution.py
Labels: bug

#762 Add `ogden_roxburgh` using AD for `Hyperelastic`
  docs/felupe/constitution.rst
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/_view.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_ogden_roxburgh.py
  tests/test_constitution.py
Labels: enhancement

#764 Add `ConstitutiveMaterial.optimize(relative=False)`
  CHANGELOG.md
  src/felupe/constitution/_base.py
  tests/test_constitution.py
Labels: enhancement

#766 Add the Micro-Sphere hyperelastic material model framework
  CHANGELOG.md
  docs/felupe/constitution.rst
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/_base.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_extended_tube.py
  src/felupe/constitution/hyperelasticity/models/_miehe_goektepe_lulei.py
  src/felupe/constitution/hyperelasticity/models/_ogden_roxburgh.py
  src/felupe/constitution/hyperelasticity/models/microsphere/__init__.py
  src/felupe/constitution/hyperelasticity/models/microsphere/_chain.py
  src/felupe/constitution/hyperelasticity/models/microsphere/_framework_affine.py
  src/felupe/constitution/hyperelasticity/models/microsphere/_framework_nonaffine.py
  tests/test_constitution.py
Labels: enhancement

#768 Add `constitutive_material(Material)` decorator
  CHANGELOG.md
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/_base.py
  tests/test_constitution.py
Labels: enhancement

#770 Add the MORPH material model (by the method of representative directions)
  CHANGELOG.md
  docs/felupe/constitution.rst
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_morph.py
  src/felupe/constitution/hyperelasticity/models/_ogden_roxburgh.py
  src/felupe/constitution/hyperelasticity/models/microsphere/__init__.py
  src/felupe/constitution/hyperelasticity/models/microsphere/_framework_affine.py
  src/felupe/mesh/_geometry.py
  tests/test_constitution.py
Labels: enhancement

#771 Add the MORPH material model formulation
  CHANGELOG.md
  docs/felupe/constitution.rst
  pyproject.toml
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_morph.py
  tests/test_constitution.py
Labels: enhancement

#774 Rebase `morph_representative_directions()` as Total-Lagrange material for `MaterialAD`
  CHANGELOG.md
  docs/felupe/constitution/hyperelasticity.rst
  docs/felupe/constitution/lagrange.rst
  examples/ex13_morph-rubber-wheel.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_morph_representative_directions.py
  src/felupe/constitution/lagrange/models/__init__.py
  src/felupe/constitution/lagrange/models/_morph_representative_directions.py
  src/felupe/constitution/lagrange/models/_morph_uniaxial.py
  src/felupe/constitution/lagrange/models/microsphere/__init__.py
  src/felupe/constitution/lagrange/models/microsphere/_framework_affine.py
  tests/test_constitution.py
Labels: enhancement

#775 Add the Anssari-Benam Bucchi isotropic-hyperelastic material model formulation
  CHANGELOG.md
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_anssari_benam_bucchi.py
  tests/test_constitution.py
Labels: enhancement

#778 Don't update the material parameters in-place and don't convert them to arrays in `ConstitutiveMaterial.optimize()`
  CHANGELOG.md
  src/felupe/constitution/_base.py
Labels: bug

#779 Add the Lopez-Pamies hyperelastic model `lopez_pamies(mu, alpha)`
  CHANGELOG.md
  src/felupe/__init__.py
  src/felupe/constitution/__init__.py
  src/felupe/constitution/hyperelasticity/models/__init__.py
  src/felupe/constitution/hyperelasticity/models/_lopez_pamies.py
  tests/test_constitution.py
Labels: enhancement

#781 Fix small typo cartesion -> cartesian
  docs/felupe/assembly.rst
Labels: documentation

#780 add example for nonlinear viscoelasticity
  README.md
  examples/ex18_nonlinear-viscoelasticity-newton.py
Labels: documentation

#784 Reset state variables in `PlotMaterial.evaluate()` after each completed load case
  CHANGELOG.md
  src/felupe/__about__.py
  src/felupe/constitution/_view.py
Labels: bug

#785 Add `math.solve_nd(A, b, n=1)`
  CHANGELOG.md
  examples/ex18_nonlinear-viscoelasticity-newton.py
  src/felupe/math/__init__.py
  src/felupe/math/_solve.py
Labels: enhancement
